# Generated by Django 2.2 on 2020-08-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200801_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('-create_at',), 'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
    ]
